language: elixir
sudo: false
elixir:
  - 1.3.4
  - 1.4.0
otp_release:
  - 18.3
  - 19.2
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
